# Generated by Django 3.2 on 2021-04-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_auto_20210427_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
